### ISSUE TITLE
Offset-to-angle transformation

### ISSUE THREAD

**Issue by kristiantorres** [nahmed215/avo_inversion#1]
Dear Nisar,

I was reading your paper and am curious about this detail:
![image](https://user-images.githubusercontent.com/40406561/235730332-b4c4c69d-d8da-4a9f-8532-e5fcd45f7fef.png)

Thank you for clearly explaining how to perform the scaling factor computation. 

What is unclear to me is how you did the offset-to-angle transformation. What equation did you use? Could you explain that to me or indicate a reference so I can follow the computation of angle gathers from the Finite Difference gathers?

Thank you, and congratulations on your published paper.

**Comment by nahmed215** [comment]
Hi Kristian,

Thanks for your email and for showing interest in our paper. For NMO, we
have used the following equation mentioned in the text:


[image: image.png]
MATLAB Code used for offset to angle conversion:
[image: image.png]
*Regards,*
Nisar Ahmed

**Comment by kristiantorres** [comment]
Hi Nisar,

Thank you for replying. 

I can't see the images you are trying to show me. 

Regards,

**Comment by nahmed215** [comment]
![unnamed](https://user-images.githubusercontent.com/95133121/236556095-eb6e6cb8-5578-43e4-b151-74d99db45ca8.png)
![unnamed](https://user-images.githubusercontent.com/95133121/236556136-9b193617-b36e-4be5-a4af-30f634dac45e.png)
I tried to drop images here.

Regards

**Comment by kristiantorres** [comment]
Thanks Nisar!

**Comment by kristiantorres** [comment]
Sorry to bother you with this, but what is the difference between `time` and `time_i` in your code?

Regard,

**Comment by kristiantorres** [comment]
Is "time_i" the array of two-way-time values?

Sorry to bother you with this.

Regards
